# DBnomics R client ----

## 1 DBnomics: the world's economic database -----

# Explore economic data from different providers at
# https://db.nomics.world/


# The R package is available on: 
# GitHub (mirror): https://github.com/dbnomics/rdbnomics
# CRAN: https://cran.r-project.org/web/packages/rdbnomics/index.html
# GitLab: https://git.nomics.world/dbnomics/rdbnomics


# Access the package vignette with
vignette("rdbnomics")
# or at https://cran.r-project.org/web/packages/rdbnomics/vignettes/rdbnomics.html#1_DBnomics:_the_world%E2%80%99s_economic_database

# See "DBnomics R client, a tutorial" by Thomas Brand on R-bloggers
# https://www.r-bloggers.com/2018/11/dbnomics-r-client-a-tutorial/

# 2 Fetch time series by `ids` ----

# Assuming you know which series you want to download.
# You will find the series identifier `ids` on the website.
# It is defined by three values, formatted like:
# `provider_code/dataset_code/series_code`.


## 2.1 Fetch one series form the dataset 'Unemployment rate' (ZUTN) of AMECO provider ----

library(rdbnomics)
library(data.table)
library(tidyverse)
# Visit <https://db.nomics.world>.

df <- rdb(ids = "AMECO/ZUTN/EA19.1.0.0.0.ZUTN")

# The return object is a data table
colnames(df)

# Remove all observations that are NA
df <- df[!is.na(value)]

# At least ten columns are in such a data table:
# - provider_code
# - dataset_code
# - dataset_name
# - series_code
# - series_name
# - original_period (character string)
# - period (date of the first day of original_period)
# - original_value (character string)
# - value
# - @frequency (harmonized frequency generated by DBnomics)

# The other columns depend on the provider of the data set.
# They always come in pairs, for the code and the name.

# In this data frame, you have:
# - unit (code) and Unit (name)
# - geo (code) and Country (name)
# - freq (code) and Frequency (name)


# Plot the data
ggplot(
  data = df,
  mapping = aes(x = period, y = value, color = series_code)
  ) +
  geom_line(linewidth = 2) +
  dbnomics()

ggsave(filename = "unemployment-ea19.png", width = 8, height = 4)
graphics.off()


## 2.2 Fetch two series form the data set 'Unemployment rate' (ZUTN) of AMECO provider ----
df <- rdb(
  ids = c(
    "AMECO/ZUTN/EA19.1.0.0.0.ZUTN", 
    "AMECO/ZUTN/DNK.1.0.0.0.ZUTN"
    )
)

head(df)

# Remove NAs
df <- df[!is.na(value)]


# Plot the two series together
ggplot(
  data = df,
  mapping = aes(x = period, y = value, color = series_code)
  ) +
  geom_line(linewidth = 2) +
  dbnomics()

ggsave(filename = "unemployment-ea19-dnk.png", width = 8, height = 4)
graphics.off()


## 2.3 Fetch two series from different datasets of different providers
df <- rdb(
  ids = c(
    "AMECO/ZUTN/EA19.1.0.0.0.ZUTN", 
    "Eurostat/une_rt_q/Q.SA.Y15-24.PC_ACT.T.EA19"
    )
)

# Remove NAs
df <- df[!is.na(value)]

# Plot the two graphs together

ggplot(
  data = df,
  mapping = aes(x = period, y = value, color = series_code)
  ) +
  geom_line(linewidth = 2) +
  dbnomics()

ggsave(filename = "unemployment-active-population.png", width = 8, height = 4)
graphics.off()


## 3 Fetch time series by `mask` ----

# The code `mask` notation is a concise way to select
# one or many time series at once.


### 3.1 Fetch one series from data set 'Balance of Payments' (BOP) of IMF ----

df <- rdb(
  provider_code = "IMF", 
  dataset_code = "BOP", 
  mask = "A.FR.BCA_BP6_EUR"
)

# Remove NAs
df <- df[!is.na(value)]

ggplot(
  data = df,
  mapping = aes(x = period, y = value, color = series_code)
  ) +
  geom_step(linewidth = 2) +
  dbnomics()

ggsave(filename = "imf-balance-of-payments.png", width = 8, height = 4)
graphics.off()


# In the event that you only use the arguments
# `provider_code`, `dataset_code` and  `mask`,
# you can drop the name `mask` and run
df <- rdb("IMF", "BOP", "A.FR.BCA_BP6_EUR")


### 3.2 Fetch two series from data set 'Balance of Payments' (BOP) of IMF ----

# You just have to add a plus sign (`+`) between two different values
# of a dimension.
df <- rdb(
  provider_code = "IMF",
  dataset_code = "BOP",
  mask = "A.FR+DE.BCA_BP6_EUR" # France + Germany
)

# Remove NAs
df <- df[!is.na(value)]


ggplot(
  data = df,
  mapping = aes(x = period, y = value, color = series_code)
  ) +
  geom_step(linewidth = 2) +
  dbnomics()

ggsave(filename = "imf-balance-of-payments-de-fr.png", width = 8, height = 4)
graphics.off()


### 3.3 Fetch all series along one dimension from data set 'Balance of Payments' (BOP) of IMF ----

df <- rdb(
  provider_code = "IMF",
  dataset_code = "BOP",
  mask = "A..BCA_BP6_EUR"
)

# Remove NAs
df <- df[!is.na(value)]

# Rearrange the data table
df <- df[order(-period, REF_AREA)]

# Take the first 100 observations
df <- head(df, n = 100)


### 3.4 Fetch series along multiple dimensions from data set 'BAlance of Payments' (BOP) of IMF ----

df <- rdb(
  provider_code = "IMF",
  dataset_code = "BOP",
  mask = "A.FR.BCA_BP6_EUR+IA_BP6_EUR"
)

# Remove NAs
df <- df[!is.na(value)]

# Reorder the data table
df <- df[order(period), head(.SD, n = 50), by = INDICATOR]

head(df)


## 4 Fetch time series by `dimensions` ----

# Searching by `dimensions` is a less concise way to
# select time series than using the code `mask`, but it
# works with all the different providers.

# There is a "Description of series code" at the bottom
# of each data set page on the DBnomics website.
# https://db.nomics.world/


## 4.1 Fetch one value of one dimension form data set 'Unemployment rate' (ZUTN) of AMECO provider ----

df <- rdb(
  provider_code = "AMECO",
  dataset_code = "ZUTN",
  dimensions = list(geo = "ea19")
)

# Remove NAs
df <- df[!is.na(value)]


ggplot(
  data = df,
  mapping = aes(x = period, y = value, color = series_code)
  ) +
  geom_step(linewidth = 2) +
  dbnomics()

# ggsave(filename = "imf-balance-of-payments-de-fr.png", width = 8, height = 4)
graphics.off()


### 4.2 Fetch two values of one dimension from dataset 'Unemployment rate' (ZUTN) of AMECO provider ----

df <- rdb(
  provider_code = "AMECO",
  dataset_code = "ZUTN",
  dimensions = list(geo = c("ea19", "dnk"))
)

# Remove NAs
df <- df[!is.na(value)]

ggplot(
  data = df,
  mapping = aes(x = period, y = value, color = series_code)
  ) +
  geom_step(linewidth = 2) +
  dbnomics()

# ggsave(filename = "imf-balance-of-payments-de-fr.png", width = 8, height = 4)
graphics.off()


### 4.3 Fetch several values of several dimensions from 'Doing buisness' (DB) of World Bank ----

df <- rdb(
  provider_code = "WB",
  dataset_code = "DB",
  dimensions = list(country = c("DZ", "PE")),
  indicator = c("ENF.CONT.COEN.COST.ZS", "IC.REG.COST.PC.FE.ZS")
)

# Reomove NAs
df <- df[is.na(value)]


### 5.1 Fetch one series from dataset 'WEO by countries (2019-10 release)' (WEO:2019-10) of IMF ----

df <- rdb(
  provider_code = "IMF",
  dataset_code = "WEO:2019-10",
  query = "France current account balance percent"
)

# Remove NAs
df <- df[!is.na(value)]

ggplot(
  data = df,
  mapping = aes(x = period, y = value, color = series_code)
  ) +
  geom_step(linewidth = 2) +
  dbnomics()

ggsave(filename = "imf-weo-france-current-account-pct.png", width = 8, height = 4)
graphics.off()


### 5.2 Fetch multiple series from dataset 'WEO by countries (2019-10 release)' (WEO:2019-10) of IMF

df <- rdb(
  provider_code = "IMF",
  dataset_code = "WEO:2019-10",
  query = "current account balance percent"
)

# Remove NAs
df <- df[!is.na(value)]

df <- df[df$`weo-country` %in% c("FRA", "DEU", "ITA", "ESP")]

unique(df$`weo-country`)

ggplot(
  data = df,
  mapping = aes(x = period, y = value, color = series_code)
  ) +
  geom_step(linewidth = 2) +
  dbnomics()

ggsave(filename = "imf-weo-fra-deu-ita-esp.png", width = 8, height = 4)
graphics.off()


## 6 Fetch time series found on the website ----

# When you don't know the codes of the dimensions, 
# provider, dataset or series, you can:

# - go to the DBnomics website, like the World Bank
#   Ease of Doing Buisness Index https://db.nomics.world/WB/DB

# - select some dimensions by using the input widgets of the left column

# - In the menu "Download", click the "Copy API link"

# - use the `dbnomics::rdb(api_link = ...)` function

df <- rdb(api_link = "https://api.db.nomics.world/v22/series/WB/DB?dimensions=%7B%22country%22%3A%5B%22FR%22%2C%22IT%22%2C%22ES%22%5D%7D&q=IC.REG.PROC.FE.NO&observations=1&format=json&align_periods=1&offset=0&facets=0")

df <- df[!is.na(value)]

# Unfortunately, the World Bank Ease of Doing Business Index
# was abolished after it was found that the economists responsible
# manipulated the data.

# In the event that you only use the argument `api_link`,
# you can drop the name and run:
df <- rdb("https://api.db.nomics.world/v22/series/WB/DB?dimensions=%7B%22country%22%3A%5B%22FR%22%2C%22IT%22%2C%22ES%22%5D%7D&q=IC.REG.PROC.FE.NO&observations=1&format=json&align_periods=1&offset=0&facets=0")


## 7 Fetch time series from the cart ----

# On the "Cart" page of the DBnomics website,
# https://db.nomics.world
# click on the "Copy API link" in the "Download" menu 
# and copy-paste it as an argument of the 
# `rdbnomics::rdb(api_link = ...)` function.

# Note that when you update your cart, 
# you have to copy this link again,
# because the link itself contains the `ids` of the series
# in the chart.

df <- rdb(api_link = "https://api.db.nomics.world/v22/series?observations=1&series_ids=BOE/6008/RPMTDDC,BOE/6231/RPMTBVE")

df <- df[!is.na(value)]

ggplot(
  data = df,
  mapping = aes(x = period, y = value, color = series_code)
  ) +
  geom_step(linewidth = 2) +
  dbnomics()

ggsave(filename = "sterling-deposits-net-lending.png", width = 8, height = 4)
graphics.off()


## 8 Fetch the available data sets of a provider ----

# When fetching a series from DBnomics, you need to
# give a provider and a data set before specifying
# correct dimensions.

# With the function `rdb_datasets`, you can download
# the list of available datasets for a provider.


### 8.1 IMF ----

# Check out the available data sets from the International Monetary Fund (IMF):
rdb_datasets(provider_code = "IMF")

# WEO by country (groups): WEO(AGG):YYYY-04/10
# Sub-Saharan Africa Regional Economic Outlook (AFRREO)
# Asia and Pacific Regional Economic Outlook (APDREO)
# Middle East and Central Asia Regional Economic Outlook (MCDREO)
# Western Hemisphere Regional Economic Outlook (WHDREO)
# Balance of Payments (BOP)
# Currency Composition of Official Foreign Exchange Reserves (COFER)
# Consumer Price Index (CPI)
# Principal Global Indicators (PGI)
# International Reserves and Foreign Currency Liquidity (IRFCL)
# Historical Public Debt (HPDD)
# International Financial Statistics (IFS)
# Fiscal Monitor (FM)


### 8.2 WB ----

# Check out data sets from the World Bank (WB)
rdb_datasets(provider_code = "WB")
# DBS - Doing Business
# GEM - Global Economic Monitor
# GEP - Global Economic Prospects
# JED - Joint External Debt Hub
# JOB - Jobs
# GDB/GDS - Quarterly External Debt Statistics GDDS/SDDS
# WDI - World Development Indicators
# WGI - Worldwide Governance Indicators
# commodity_prices - Commodity Prices: History and Projections


### 8.3 ECB ----

# Check out data sets from the European Central Bank (ECB)
ecb <- rdb_datasets(provider_code = "ECB")
ecb <- as_tibble(ecb)
View(ecb)

# CISS - Composite Indicator of Systemic Stress
# CLIFS - Country-Level Index of Financial Stress (CLIFS)

# EST - Euro Short-Term Rate
# EXR - Exchange Rates
# FM - Financial market data
# FXI - Foreign Exchange Statistics

# ICP - Indices of Consumer prices

# IRS - Interest rate statistic

# VC - Eurostat Job Vacancy Statistics
# JVS - Job Vacancy Statistics
# KRI - EBA Key Risk Indicators
# LCI - Labour Cost Indices

# SPF - Survey of Professional Forecasters
# BLS - Bank Lending Survey Statistics
# SUR - Opinion Surveys
# TRD - External Balances
# TRD - External Trade
# WTS - Trade weights
# YC - Financial market data - yield curve


### 8.4 OECD ----

# Check out data from the OECD
rdb_datasets(provider_code = "OECD")
# ADIMA - OECD ADIMA 500 Google Trends Monitor
# CSPCUBE - Country statistical profiles
# EO - Economic Outlook No 114 - November 2023.
# GDP_GROWTH - Weekly tracker of economic activity (GDP growth)
# HOUSE_PRICES - Analytical house prices indicators
# IOTS_2021 - Input-Output Tables (IOTs) 2021 ed.
# KEI - Key Short-Term Economic Indicators
# MEI - Main Economic Indicators Publication
# MEI_CLI - Composite Leading Indicators (MEI)
# NAAG - National Accounts at a Glance
# QITS - Quarterly International Trade Statistics (by partner country)
# QNA - Quarterly National Accounts


### 8.5 Eurostat ----
# Check out data from Eurostat
eurostat <- rdb_datasets(provider_code = "Eurostat") |> 
  as_tibble()

# Literally thousands of data sets (!)


### 8.6 Mulitple providers ----

# Some data sets are available from multiple providers.
# Get a named list of the union
rdb_datasets(provider_code = c("IFM", "BDF"))
# AME - Macro Economy - Euro Area
# BLS - Bank Lending Survey
# BSI - Monetary Statistics - Eur Area
# CFT - Quarterly financial accounts
# ECOFI - ECOFIN : Economy and Finance
# ESA - ESA95 National Accounts
# ESTR - Euro short-term rate  - €STR
# EXR - Exchange Rates
# FCI - Banque de France Financial Conditions Index (BdF FCI)
# FM - Financial Market Data
# ICP - Indexes of Consumer Price
# MNA - National Accounts Main Aggregates
# SI_AI - Inflation Anticipation


### 8.7 All data sets in DBnomics ----

# The extent of data sets gathered by DBnomics can be 
# appreciated with the function argument `provider_code`
# set to `NULL`:
options(rdbnomics.progress_bar_datasets = TRUE)
rdb.l <- rdb_datasets()
options(rdbnomics.progress_bar_datasets = FALSE)

names(rdb.l)

# Check out https://db.nomics.world/providers

